{"items"=>
  [
    {
      "id"=>"36315174",
      "premium"=>false,
      "name"=>"Junior разработчик Ruby on Rails",
      "department"=>nil,
      "has_test"=>false,
      "response_letter_required"=>false,
      "area"=>
        {"id"=>"1",
         "name"=>"Москва",
         "url"=>"https://api.hh.ru/areas/1"
        },
      "salary"=>
        {
          "from"=>40000,
          "to"=>80000,
          "currency"=>"RUR",
          "gross"=>false
        },
      "type"=>
        {
          "id"=>"open",
          "name"=>"Открытая"
        },
      "address"=>
        {
          "city"=>"Москва",
          "street"=>"Новорязанская улица",
          "building"=>"18с11",
          "description"=>nil,
          "lat"=>55.7703749989,
          "lng"=>37.6604122884,
          "raw"=>"Москва, Новорязанская улица, 18с11",
          "metro"=>
            {
              "station_name"=>"Комсомольская",
              "line_name"=>"Сокольническая",
              "station_id"=>"1.54",
              "line_id"=>"1",
              "lat"=>55.774072,
              "lng"=>37.654565},
          "metro_stations"=>
            [
              {
                "station_name"=>"Комсомольская",
                "line_name"=>"Сокольническая",
                "station_id"=>"1.54",
                "line_id"=>"1",
                "lat"=>55.774072,
                "lng"=>37.654565
              }
            ],
          "id"=>"760446"
        },
      "response_url"=>nil,
      "sort_point_distance"=>nil,
      "employer"=>
        {
          "id"=>"1805574",
          "name"=>"Инсейлс Рус",
          "url"=>"https://api.hh.ru/employers/1805574",
          "alternate_url"=>"https://hh.ru/employer/1805574",
        "logo_urls"=>
            {
              "90"=>"https://hhcdn.ru/employer-logo/2070634.jpeg",
              "original"=>"https://hhcdn.ru/employer-logo-original/407139.jpg",
              "240"=>"https://hhcdn.ru/employer-logo/2070635.jpeg"
            },
          "vacancies_url"=>"https://api.hh.ru/vacancies?employer_id=1805574",
          "trusted"=>true
        },
      "published_at"=>"2020-04-18T15:26:32+0300",
      "created_at"=>"2020-04-18T15:26:32+0300",
      "archived"=>false,
      "apply_alternate_url"=>"https://hh.ru/applicant/vacancy_response?vacancyId=36315174",
      "insider_interview"=>nil,
      "url"=>"https://api.hh.ru/vacancies/36315174?host=hh.ru",
      "alternate_url"=>"https://hh.ru/vacancy/36315174",
      "relations"=>[],
      "snippet"=>
        {
          "requirement"=>"Знание теории алгоритмов и структур данных. Знание языка <highlighttext>Ruby</highlighttext> и базовые знания фреймворка <highlighttext>Ruby</highlighttext> <highlighttext>on</highlighttext> <highlighttext>Rails</highlighttext>. Знание SQL и теории...",
          "responsibility"=>"Решать интересные задачи по развитию сервиса, помогать коллегам писать их код еще лучше, участвовать в проектировании новых фич для пользователей..."
        },
      "contacts"=>nil
    }
  ]
}